services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    
    ports:
      - "${PORT}:${PORT}"

    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}

    env_file:
      - .env

    depends_on:
      - db
    
    restart: unless-stopped

  db:
    image: mongo:6
    
    ports:
      - "${MONGO_PORT}:27017"
    
    environment:
      MONGO_INITDB_DATABASE: ${DATABASE_NAME}
    
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
      
    restart: unless-stopped

volumes:
  mongodb_data: